package com.luxottica.testautomation.constants;

public class Label {

    public static final String ENDPONT = "labels.endpoint";
    public static final String HEADER_KEY = "labels.header.key";
    public static final String HEADER_VALUE = "labels.header.value";

    public static final String COOKIE_POLICY_BANNER_MESSAGE = "COOKIE_POLICY_BANNER_MESSAGE";
    public static final String COOKIE_POLICY_BANNER_REFUSE = "COOKIE_POLICY_BANNER_REFUSE";
    public static final String SRP_DISCLAIMER_DESCRIPTION = "SRP_DISCLAIMER_DESCRIPTION";
    public static final String ALL_PRICES = "ALL_PRICES";
    public static final String PLP_SORT_BY_ALPHABETICAL = "PLP_SORT_BY_ALPHABETICAL";
    public static final String PLP_SORT_BY_BESTSELLER = "PLP_SORT_BY_BESTSELLER";
    public static final String PLP_SORT_BY_NEW = "PLP_SORT_BY_NEW";
    public static final String PLP_SORT_BY_RELEVANCE = "PLP_SORT_BY_RELEVANCE";
    public static final String AFTERSALES_CONVERSATIONAL_VIEW_SPAREPARTS_CTA = "AFTERSALES_CONVERSATIONAL_VIEW_SPAREPARTS_CTA";
    public static final String AFTERSALES_CONVERSATIONAL_SEARCH_BRAND_PLACEHOLDER = "AFTERSALES_CONVERSATIONAL_SEARCH_BRAND_PLACEHOLDER";
    public static final String AFTERSALES_CONVERSATIONAL_SEARCH_MODEL_PLACEHOLDER = "AFTERSALES_CONVERSATIONAL_SEARCH_MODEL_PLACEHOLDER";
    public static final String AFTERSALES_CONVERSATIONAL_SEARCH_VARIANT_PLACEHOLDER = "AFTERSALES_CONVERSATIONAL_SEARCH_VARIANT_PLACEHOLDER";
    public static final String AFTERSALES_CONVERSATIONAL_PLACE_WARRANTY_CTA = "AFTERSALES_CONVERSATIONAL_PLACE_WARRANTY_CTA";
    public static final String WARRANTY_DAMAGE_INFO_DROPDOWN_DEFECT_PLACEHOLDER = "WARRANTY_DAMAGE_INFO_DROPDOWN_DEFECT_PLACEHOLDER";
    public static final String WARRANTY_DAMAGE_INFO_DROPDOWN_STATE_OF_SALE_PLACEHOLDER = "WARRANTY_DAMAGE_INFO_DROPDOWN_STATE_OF_SALE_PLACEHOLDER";
    public static final String WARRANTY_DAMAGE_INFO_DROPDOWN_TYPE_OF_REQUEST_PLACEHOLDER = "WARRANTY_DAMAGE_INFO_DROPDOWN_TYPE_OF_REQUEST_PLACEHOLDER";
    public static final String WARRANTY_LUX_WARR_SELECT_TYPE_OF_REQUEST_VALUE_NAME_STANDARD = "WARRANTY_LUX_WARR_SELECT_TYPE_OF_REQUEST_VALUE_NAME.STANDARD";
    public static final String WARRANTY_DAMAGE_INFO_STICKY_BAR_BUTTON_LABEL = "WARRANTY_DAMAGE_INFO_STICKY_BAR_BUTTON_LABEL";

    public static final String RX_CHOOSE_BRAND = "RX_CHOOSE_BRAND";
}
