logging:
  level:
    com.luxottica.testautomation: TRACE
myel:
  baseUrl: "https://certi-my.essilorluxottica.com"
  endpoints:
    sessionUrl: "/fo-bff/admin/current-session"
    personificationUrl: "/fo-bff/api/priv/v1/{storeIdentifier}/{locale}/personification/customers"
    precart: "/fo-bff/api/priv/v1/{storeIdentifier}/{locale}/precart"
    doors: "fo-bff/api/priv/v1/{storeIdentifier}/{locale}/doors"
    usercontext: "/fo-bff/api/priv/v1/{storeIdentifier}/usercontext"
    facets: "/fo-bff/api/priv/v1/{storeIdentifier}/{locale}/search/byFacets/*"
search:
  baseUrl: "https://search.myluatlive.luxottica.com"
  endpoints:
    findProductsByCategoryCarousel: "/search/resources/store/{storeIdentifier}/productview/byCategory/{categoryId}?profileName=LX_findProductsByCategoryCarousel"
labels:
    endpoint: 'https://api-hub-prod.luxottica.com/translations/getPrivateTranslations?project=MYEL - Front Office&isExtended=false&language={locale}'
    header:
      key: 'Ocp-Apim-Subscription-Key'
      value: '52341fb04f5b493caebe08689b6750d7'
